list = [5, True, 7.4, 'hello', None, 3.14, False, 42, 'world', 0]
print(len(list))
list.append('new item')
print(list)
list.insert(1, 'inserted item')
print(list)
list.pop(4)
print(list)
list.remove(0)
print(list)